name: dtg
description: Dart to Go! An excellent utility provided with simplicity.
version: 1.0.3
homepage: https://github.com/andypangaribuan/DTG

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
